name: 'Label Questions as Stale'

# use narrower default job permissions
permissions:
  # XXX not sure what all this entails, but there doesn't seem to be something to limit to issue reading+labeling+commenting
  issues: write

on:
  # manual button press:
  workflow_dispatch:
  # TODO add cron schedule here + add issue opener workflow (that warns about DST issues)

jobs:
  Label-Questions-as-Stale:
    runs-on: ubuntu-latest
    environment: TestEnvironment001
    steps:
     - id: stale_labeler
       # https://blog.gitguardian.com/github-actions-security-cheat-sheet/ recommends using commit hashes to avoid supply-chain attacks
       # FIXME but what about security patches?
       # 
       # FIXME but if there is a rewrite&force-push or some other breakage?  How do we effectively ping people to see?
       uses: actions/stale@532554b8a8498a0e006fbcde824b048728c4178f
       with:
         # idea is to have cron run this only at points where the "questions" (actually, scheduled tasks) will be stale.
         # OR fractional days + frequent runs, and just hope for no queueing delays on the issue opener workflow?
         days-before-stale: 0
         days-before-close: -1
         # XXX not sure if this filters issues+PRs down to issues with this label VS. only filters issues -> issues with this label and keeps all PRs
         only-issue-labels: 'question'
         stale-issue-message: 'Marking this question as stale.  This should also trigger a related Slack workflow.'
     - name: Print outputs of `actions/stale`
       run: echo ${{ join(steps.stale_labeler.outputs.*, ',') }}
     - name: Run notification webhook if `actions/stale` appears to have labeled or closed anything
       if: join(steps.stale_labeler.outputs.*, ',') != '[],[]'
       run: curl --request POST ${{ secrets.STALE_QUESTION_NOTIFY_WEBHOOK }}
       
